alter table if exists armia drop constraint if exists FK3ju7l4qs4lvgw0u5u1iql14au;
alter table if exists brigada drop constraint if exists FKaa39uqs31iimkemb3bkdmh2pp;
alter table if exists brigada drop constraint if exists FK2rtunq2xlu39dq0bkeclmd4r8;
alter table if exists divizia drop constraint if exists FK8dg8tnaokkwhfjhncf0nfyouc;
alter table if exists divizia drop constraint if exists FKe2p3u2wonpoucat1m1aignxvm;
alter table if exists efreytor drop constraint if exists FKoghai9hbhmflmxy1pwxfvow94;
alter table if exists general drop constraint if exists FKd9dqu48ba5ks1ga19pdvx429d;
alter table if exists kapitan drop constraint if exists FK63eaw2dwemrfn4poa395nd5dj;
alter table if exists korpus drop constraint if exists FKntxmp8m35n8rp7ks37vhqv9tw;
alter table if exists korpus drop constraint if exists FKhoaj8hsoy0vnr2anfw8ceerdb;
alter table if exists leytenant drop constraint if exists FKad48igpoprw6vu1jj8gsyvr8h;
alter table if exists maior drop constraint if exists FK487jnw3re14kq7yfglxrc5i94;
alter table if exists oficer_sostav drop constraint if exists FKhdehax7qoq7fgkwrf5umscmli;
alter table if exists otdelenie drop constraint if exists FKmro7w4kr1wfjidk1sf5fvx8r6;
alter table if exists otdelenie drop constraint if exists FKri6mn49v1b2a1bgxmdtgee2u3;
alter table if exists person drop constraint if exists FK3p75h7c73rfdvc8c02rg3kqlr;
alter table if exists podpolkovnik drop constraint if exists FK3pfhbnhfjx7vajib28jr5qe3g;
alter table if exists polkovnik drop constraint if exists FK8o65t3glkvvsqda6rejsjj786;
alter table if exists praporshik drop constraint if exists FKjcxye2a3bdygshxmtv3jsspby;
alter table if exists rota drop constraint if exists FKnhntrxko0dsk79vrmlt68ve49;
alter table if exists rota drop constraint if exists FKgtngc8cpivpb98srianf8mtqe;
alter table if exists ryadovoy_model drop constraint if exists FKipk8eydkcgl1jbp2hfv5thgeq;
alter table if exists ryadovoy_sostav drop constraint if exists FKft5o2amjxj3ys0ntus6bf06x4;
alter table if exists ryadovoy_sostav drop constraint if exists FKmerru5wbcpbv95jrqnfxthr14;
alter table if exists serzhant drop constraint if exists FKmw3gn6b6deisijhvyk5ys2br8;
alter table if exists starshina drop constraint if exists FK47f8nf6vp4yop1bbs3pteslrn;
alter table if exists voinskaya_chast drop constraint if exists FKh0wg2fldyohe95eyd1qgfoeos;
alter table if exists voinskaya_chast drop constraint if exists FKkpy0fxeekv4o0ay1i5uc60rsk;
alter table if exists vzvod drop constraint if exists FKbahnov3t0i3xeji32juok1rei;
alter table if exists vzvod drop constraint if exists FKcnvf6tfktl0fd98elclhjdll7;
drop table if exists armia cascade;
drop table if exists artilleria cascade;
drop table if exists automat_oruzhie cascade;
drop table if exists autotransport cascade;
drop table if exists bmp cascade;
drop table if exists brigada cascade;
drop table if exists divizia cascade;
drop table if exists efreytor cascade;
drop table if exists general cascade;
drop table if exists kapitan cascade;
drop table if exists karabin cascade;
drop table if exists korpus cascade;
drop table if exists leytenant cascade;
drop table if exists maior cascade;
drop table if exists oficer_sostav cascade;
drop table if exists otdelenie cascade;
drop table if exists person cascade;
drop table if exists podpolkovnik cascade;
drop table if exists polkovnik cascade;
drop table if exists praporshik cascade;
drop table if exists raketnoe_oruzhie cascade;
drop table if exists rota cascade;
drop table if exists ryadovoy_model cascade;
drop table if exists ryadovoy_sostav cascade;
drop table if exists serzhant cascade;
drop table if exists sooruzhenie cascade;
drop table if exists starshina cascade;
drop table if exists transport cascade;
drop table if exists tyagach cascade;
drop table if exists usr cascade;
drop table if exists voinskaya_chast cascade;
drop table if exists vooruzhenie cascade;
drop table if exists vzvod cascade;
drop sequence if exists hibernate_sequence;